name: Build Android APK with Buildozer

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libncurses5:i386 libstdc++6:i386 libgtk-3-dev libz3-dev zlib1g:i386 unzip ant openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.34

      - name: Build with Buildozer
        run: |
          # Устанавливаем пути для buildozer, чтобы он нашел Java
          export JAVA_HOME=/usr/lib/jvm/zulu-11-amd64/
          buildozer android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrueScanner-APK
          path: bin/*.apk
          if-no-files-found: error # Если APK не создался, сборка упадет с ошибкой